//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("test_francaisModel", "FK__question_e__id_n__21B6055D", "cordonner", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(test_Francais_kg.cordonner), "question_exam", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(test_Francais_kg.question_exam), true)]

#endregion

namespace test_Francais_kg
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class test_francaisEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet test_francaisEntities à l'aide de la chaîne de connexion trouvée dans la section 'test_francaisEntities' du fichier de configuration d'application.
        /// </summary>
        public test_francaisEntities() : base("name=test_francaisEntities", "test_francaisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet test_francaisEntities.
        /// </summary>
        public test_francaisEntities(string connectionString) : base(connectionString, "test_francaisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet test_francaisEntities.
        /// </summary>
        public test_francaisEntities(EntityConnection connection) : base(connection, "test_francaisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<cordonner> cordonner
        {
            get
            {
                if ((_cordonner == null))
                {
                    _cordonner = base.CreateObjectSet<cordonner>("cordonner");
                }
                return _cordonner;
            }
        }
        private ObjectSet<cordonner> _cordonner;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<exam> exam
        {
            get
            {
                if ((_exam == null))
                {
                    _exam = base.CreateObjectSet<exam>("exam");
                }
                return _exam;
            }
        }
        private ObjectSet<exam> _exam;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<lesquestion> lesquestion
        {
            get
            {
                if ((_lesquestion == null))
                {
                    _lesquestion = base.CreateObjectSet<lesquestion>("lesquestion");
                }
                return _lesquestion;
            }
        }
        private ObjectSet<lesquestion> _lesquestion;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<question_exam> question_exam
        {
            get
            {
                if ((_question_exam == null))
                {
                    _question_exam = base.CreateObjectSet<question_exam>("question_exam");
                }
                return _question_exam;
            }
        }
        private ObjectSet<question_exam> _question_exam;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet cordonner. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTocordonner(cordonner cordonner)
        {
            base.AddObject("cordonner", cordonner);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet exam. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToexam(exam exam)
        {
            base.AddObject("exam", exam);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet lesquestion. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTolesquestion(lesquestion lesquestion)
        {
            base.AddObject("lesquestion", lesquestion);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet question_exam. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToquestion_exam(question_exam question_exam)
        {
            base.AddObject("question_exam", question_exam);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="test_francaisModel", Name="cordonner")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cordonner : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet cordonner.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        public static cordonner Createcordonner(global::System.Int32 id)
        {
            cordonner cordonner = new cordonner();
            cordonner.id = id;
            return cordonner;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Imatricule
        {
            get
            {
                return _Imatricule;
            }
            set
            {
                OnImatriculeChanging(value);
                ReportPropertyChanging("Imatricule");
                _Imatricule = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Imatricule");
                OnImatriculeChanged();
            }
        }
        private global::System.String _Imatricule;
        partial void OnImatriculeChanging(global::System.String value);
        partial void OnImatriculeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cin
        {
            get
            {
                return _cin;
            }
            set
            {
                OncinChanging(value);
                ReportPropertyChanging("cin");
                _cin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cin");
                OncinChanged();
            }
        }
        private global::System.String _cin;
        partial void OncinChanging(global::System.String value);
        partial void OncinChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sexe
        {
            get
            {
                return _sexe;
            }
            set
            {
                OnsexeChanging(value);
                ReportPropertyChanging("sexe");
                _sexe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sexe");
                OnsexeChanged();
            }
        }
        private global::System.String _sexe;
        partial void OnsexeChanging(global::System.String value);
        partial void OnsexeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String datenaissance
        {
            get
            {
                return _datenaissance;
            }
            set
            {
                OndatenaissanceChanging(value);
                ReportPropertyChanging("datenaissance");
                _datenaissance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("datenaissance");
                OndatenaissanceChanged();
            }
        }
        private global::System.String _datenaissance;
        partial void OndatenaissanceChanging(global::System.String value);
        partial void OndatenaissanceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pass
        {
            get
            {
                return _pass;
            }
            set
            {
                OnpassChanging(value);
                ReportPropertyChanging("pass");
                _pass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pass");
                OnpassChanged();
            }
        }
        private global::System.String _pass;
        partial void OnpassChanging(global::System.String value);
        partial void OnpassChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> valide
        {
            get
            {
                return _valide;
            }
            set
            {
                OnvalideChanging(value);
                ReportPropertyChanging("valide");
                _valide = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valide");
                OnvalideChanged();
            }
        }
        private Nullable<global::System.Boolean> _valide;
        partial void OnvalideChanging(Nullable<global::System.Boolean> value);
        partial void OnvalideChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nomutilisateur
        {
            get
            {
                return _nomutilisateur;
            }
            set
            {
                OnnomutilisateurChanging(value);
                ReportPropertyChanging("nomutilisateur");
                _nomutilisateur = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nomutilisateur");
                OnnomutilisateurChanged();
            }
        }
        private global::System.String _nomutilisateur;
        partial void OnnomutilisateurChanging(global::System.String value);
        partial void OnnomutilisateurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CULTUR
        {
            get
            {
                return _CULTUR;
            }
            set
            {
                OnCULTURChanging(value);
                ReportPropertyChanging("CULTUR");
                _CULTUR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CULTUR");
                OnCULTURChanged();
            }
        }
        private Nullable<global::System.Boolean> _CULTUR;
        partial void OnCULTURChanging(Nullable<global::System.Boolean> value);
        partial void OnCULTURChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> langue
        {
            get
            {
                return _langue;
            }
            set
            {
                OnlangueChanging(value);
                ReportPropertyChanging("langue");
                _langue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("langue");
                OnlangueChanged();
            }
        }
        private Nullable<global::System.Boolean> _langue;
        partial void OnlangueChanging(Nullable<global::System.Boolean> value);
        partial void OnlangueChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("test_francaisModel", "FK__question_e__id_n__21B6055D", "question_exam")]
        public EntityCollection<question_exam> question_exam
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<question_exam>("test_francaisModel.FK__question_e__id_n__21B6055D", "question_exam");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<question_exam>("test_francaisModel.FK__question_e__id_n__21B6055D", "question_exam", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="test_francaisModel", Name="exam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class exam : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet exam.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        public static exam Createexam(global::System.Int32 id)
        {
            exam exam = new exam();
            exam.id = id;
            return exam;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cin
        {
            get
            {
                return _cin;
            }
            set
            {
                OncinChanging(value);
                ReportPropertyChanging("cin");
                _cin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cin");
                OncinChanged();
            }
        }
        private global::System.String _cin;
        partial void OncinChanging(global::System.String value);
        partial void OncinChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private Nullable<global::System.Int32> _Note;
        partial void OnNoteChanging(Nullable<global::System.Int32> value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type_ques
        {
            get
            {
                return _Type_ques;
            }
            set
            {
                OnType_quesChanging(value);
                ReportPropertyChanging("Type_ques");
                _Type_ques = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type_ques");
                OnType_quesChanged();
            }
        }
        private global::System.String _Type_ques;
        partial void OnType_quesChanging(global::System.String value);
        partial void OnType_quesChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="test_francaisModel", Name="lesquestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lesquestion : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet lesquestion.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        public static lesquestion Createlesquestion(global::System.Int32 id)
        {
            lesquestion lesquestion = new lesquestion();
            lesquestion.id = id;
            return lesquestion;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String question
        {
            get
            {
                return _question;
            }
            set
            {
                OnquestionChanging(value);
                ReportPropertyChanging("question");
                _question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("question");
                OnquestionChanged();
            }
        }
        private global::System.String _question;
        partial void OnquestionChanging(global::System.String value);
        partial void OnquestionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String choix1
        {
            get
            {
                return _choix1;
            }
            set
            {
                Onchoix1Changing(value);
                ReportPropertyChanging("choix1");
                _choix1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("choix1");
                Onchoix1Changed();
            }
        }
        private global::System.String _choix1;
        partial void Onchoix1Changing(global::System.String value);
        partial void Onchoix1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String choix2
        {
            get
            {
                return _choix2;
            }
            set
            {
                Onchoix2Changing(value);
                ReportPropertyChanging("choix2");
                _choix2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("choix2");
                Onchoix2Changed();
            }
        }
        private global::System.String _choix2;
        partial void Onchoix2Changing(global::System.String value);
        partial void Onchoix2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String choix3
        {
            get
            {
                return _choix3;
            }
            set
            {
                Onchoix3Changing(value);
                ReportPropertyChanging("choix3");
                _choix3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("choix3");
                Onchoix3Changed();
            }
        }
        private global::System.String _choix3;
        partial void Onchoix3Changing(global::System.String value);
        partial void Onchoix3Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String choixrelle
        {
            get
            {
                return _choixrelle;
            }
            set
            {
                OnchoixrelleChanging(value);
                ReportPropertyChanging("choixrelle");
                _choixrelle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("choixrelle");
                OnchoixrelleChanged();
            }
        }
        private global::System.String _choixrelle;
        partial void OnchoixrelleChanging(global::System.String value);
        partial void OnchoixrelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> valide
        {
            get
            {
                return _valide;
            }
            set
            {
                OnvalideChanging(value);
                ReportPropertyChanging("valide");
                _valide = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valide");
                OnvalideChanged();
            }
        }
        private Nullable<global::System.Boolean> _valide;
        partial void OnvalideChanging(Nullable<global::System.Boolean> value);
        partial void OnvalideChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type_ques
        {
            get
            {
                return _Type_ques;
            }
            set
            {
                OnType_quesChanging(value);
                ReportPropertyChanging("Type_ques");
                _Type_ques = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type_ques");
                OnType_quesChanged();
            }
        }
        private global::System.String _Type_ques;
        partial void OnType_quesChanging(global::System.String value);
        partial void OnType_quesChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="test_francaisModel", Name="question_exam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class question_exam : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet question_exam.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="id_n">Valeur initiale de la propriété id_n.</param>
        public static question_exam Createquestion_exam(global::System.Int32 id, global::System.Int32 id_n)
        {
            question_exam question_exam = new question_exam();
            question_exam.id = id;
            question_exam.id_n = id_n;
            return question_exam;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_n
        {
            get
            {
                return _id_n;
            }
            set
            {
                if (_id_n != value)
                {
                    Onid_nChanging(value);
                    ReportPropertyChanging("id_n");
                    _id_n = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_n");
                    Onid_nChanged();
                }
            }
        }
        private global::System.Int32 _id_n;
        partial void Onid_nChanging(global::System.Int32 value);
        partial void Onid_nChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String question
        {
            get
            {
                return _question;
            }
            set
            {
                OnquestionChanging(value);
                ReportPropertyChanging("question");
                _question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("question");
                OnquestionChanged();
            }
        }
        private global::System.String _question;
        partial void OnquestionChanging(global::System.String value);
        partial void OnquestionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String choix1
        {
            get
            {
                return _choix1;
            }
            set
            {
                Onchoix1Changing(value);
                ReportPropertyChanging("choix1");
                _choix1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("choix1");
                Onchoix1Changed();
            }
        }
        private global::System.String _choix1;
        partial void Onchoix1Changing(global::System.String value);
        partial void Onchoix1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String choixrelle
        {
            get
            {
                return _choixrelle;
            }
            set
            {
                OnchoixrelleChanging(value);
                ReportPropertyChanging("choixrelle");
                _choixrelle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("choixrelle");
                OnchoixrelleChanged();
            }
        }
        private global::System.String _choixrelle;
        partial void OnchoixrelleChanging(global::System.String value);
        partial void OnchoixrelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> compteur
        {
            get
            {
                return _compteur;
            }
            set
            {
                OncompteurChanging(value);
                ReportPropertyChanging("compteur");
                _compteur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("compteur");
                OncompteurChanged();
            }
        }
        private Nullable<global::System.Int32> _compteur;
        partial void OncompteurChanging(Nullable<global::System.Int32> value);
        partial void OncompteurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> valide
        {
            get
            {
                return _valide;
            }
            set
            {
                OnvalideChanging(value);
                ReportPropertyChanging("valide");
                _valide = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valide");
                OnvalideChanged();
            }
        }
        private Nullable<global::System.Boolean> _valide;
        partial void OnvalideChanging(Nullable<global::System.Boolean> value);
        partial void OnvalideChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type_ques
        {
            get
            {
                return _Type_ques;
            }
            set
            {
                OnType_quesChanging(value);
                ReportPropertyChanging("Type_ques");
                _Type_ques = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type_ques");
                OnType_quesChanged();
            }
        }
        private global::System.String _Type_ques;
        partial void OnType_quesChanging(global::System.String value);
        partial void OnType_quesChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("test_francaisModel", "FK__question_e__id_n__21B6055D", "cordonner")]
        public cordonner cordonner
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cordonner>("test_francaisModel.FK__question_e__id_n__21B6055D", "cordonner").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cordonner>("test_francaisModel.FK__question_e__id_n__21B6055D", "cordonner").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cordonner> cordonnerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cordonner>("test_francaisModel.FK__question_e__id_n__21B6055D", "cordonner");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cordonner>("test_francaisModel.FK__question_e__id_n__21B6055D", "cordonner", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
